 const Ks = {	  
	  cost: 19,
	  use: 19,
	  weight: 18,
	  clarity: 18,
	  smoothness: 18,
	  comfort: 18,
	  friendship: 17,
	  mood: 17,
	  gender: 17,
	  luxury: 17,
	  natural: 17,
	  scale: 16,
	  calm: 15,
	  confidence: 15,
	  beauty: 14,
	  attractiveness: 14,
	  fashion: 14,
	  expressiveness: 14,
	  proportions: 13,
	  sophistication: 13,
	  harmony: 13,
	  density: 12,
	  thinness: 12,
	  pallor: 11,
	  thickness: 11,
	  roundness: 10,
	  acute: 10,
	  modernity: 9,
	  age: 9,
	  classically: 8,
	  simple: 8,
	  noble: 8,
	  lineary: 7,
	  familiar: 6,
	  exclusive: 6,
  }
  
  const pictures = {
	  'Arial' : 'image/6.jpg',
	  'Blender Pro' : 'image/3.jpg', 
	  'Bebas' : 'image/5.jpg',
	  'Inter' : 'image/6.jpg',
	  'DecimaMonoX' : 'image/5.jpg',
	  'Kizo' : 'image/3.jpg',
	  'PF DinText Pro' : 'image/6.jpg',
	  'PT Mono' : 'image/5.jpg',
	  'TT Firs Neue' : 'image/5.jpg',
	  'Circe' : 'image/6.jpg',
	  'Futura New Book' : 'image/2.jpg',
	  'Garamond Premier Pro' : 'image/3.jpg',
	  'Intro Black Alt' : 'image/4.jpg',
	  'Muller Regular' : 'image/6.jpg',
	  'ITC New Baskerville' : 'image/3.jpg',
	  'PF Regal Pro' : 'image/3.jpg',
	  'TTCommons' : 'image/6.jpg',
	  'Helvetica Neue' : 'image/6.jpg',
	  'Museo Cyrillic' : 'image/4.jpg',
	  'Neo Sans' : 'image/4.jpg',
	  'Stolzl' : 'image/5.jpg',
	  'Uni Sans Bold' : 'image/5.jpg',
	  'Code Pro Black' : 'image/1.jpg',
	  'Druk Wide' : 'image/1.jpg',
	  'Tactic Sans' : 'image/1.jpg',
	  'TT Supermolot Neue': 'image/3.jpg',
	  'Furore' : 'image/1.jpg',
	  'Vetren' : 'image/3.jpg',
	  'Trajan Pro' : 'image/3.jpg',
	  'Candara' : 'image/5.jpg',
	  'Thin Skinned' : 'image/4.jpg',
	  'Remains' : 'image/3.jpg',
	  'Road Rage' : 'image/1.jpg',
	  'Antonella' : 'image/2.jpg',
	  'Nostalgia' : 'image/4.jpg',
	  'Rosalinda' : 'image/2.jpg',
	  'Bernhard' : 'image/2.jpg',
	  'Rotonda' : 'image/6.jpg',
	  'KillCrazye' : 'image/1.jpg',
	  'Cinzel': 'image/3.jpg',
	  'Sverdlovsk' : 'image/2.jpg',
	  'Airfool' : 'image/4.jpg',
	  'NFS font' : 'image/1.jpg',
	  'EchoRevival' : 'image/4.jpg',
	  'AGOpus' : 'image/6.jpg',
	  'Grenouille' : 'image/4.jpg',
	  'Rum Raisin Cyrillic' : 'image/4.jpg',
	  'Mont ExtraLight' : 'image/2.jpg',
	  'Hacked' : 'image/1.jpg',
	 'Monotype Corsiva' : 'image/2.jpg',
	  
  }
  
  const FONTS = [
  {
	name: 'Arial',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Blender Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Bebas',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Inter',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'DecimaMonoX',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Kizo',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'b',
	  age: 'c',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'PF DinText Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'PT Mono',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },
  {
	name: 'TT Firs Neue',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'a',
	},
  },
  {
	name: 'Circe',
	characteristics:
	{		
		cost: 'c',
		use: 'b',

	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Futura New Book',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Garamond Premier Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'a',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Intro Black Alt',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'a',
	  classically: 'b',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Muller Regular',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'ITC New Baskerville',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'PF Regal Pro',
    characteristics:
	{		
		cost: 'a',
		use: 'b',

	  weight: 'b',
	  clarity: 'c',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'TTCommons',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Helvetica Neue',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Museo Cyrillic',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Neo Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Stolzl',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Uni Sans Bold',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Code Pro Black',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Druk Wide',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Tactic Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'TT Supermolot Neue',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Furore',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Vetren',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'a',
	  calm: 'c',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Trajan Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'b',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Candara',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'Thin Skinned',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Remains',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'c',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'c',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Road Rage',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Antonella',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Nostalgia',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'c',
	  classically: 'a',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rosalinda',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Bernhard',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rotonda',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'KillCrazye',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Cinzel',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'c',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Sverdlovsk',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },
  {
	name: 'Airfool',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'NFS font',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'EchoRevival',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'AGOpus',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Grenouille',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'a',
	  beauty: 'c',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rum Raisin Cyrillic',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'c',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Mont ExtraLight',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Hacked',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Monotype Corsiva',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'a',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  



]

function myFunction() {
  var form = document.querySelector("form");
  var data = new FormData(form);
  
  const results = FONTS.map(f => {
	  const characteristics = Object.keys(f.characteristics);
	  
	  const score = characteristics.reduce((res, character) => {
		  const userValue = data.get(character) || "b";
		  const k = Ks[character];
		  
		  let charScore = userValue === f.characteristics[character] ? 1 : -1;
		  if (userValue=="b" || f.characteristics[character]=="b") {
			  charScore = 0;
		  }
		  return res + charScore * k;
		  
	  }, 0);
	  
	  return {
		  name: f.name,
		  score: score
	  }
	  
  })
  
  console.log(results);
  
  results.sort(function(a,b){return b.score-a.score});
  
   
  document.getElementById("results").style.display="block";
  document.getElementById("first").textContent="1. " + results[0].name;
  document.getElementById("second").textContent="2. " + results[1].name;
  document.getElementById("third").textContent="3. " + results[2].name;
  document.getElementById("fourth").textContent="4. " + results[3].name;
  document.getElementById("fifth").textContent="5. " + results[4].name;
  
  document.getElementById("picture").src=pictures[results[0].name];
  
  document.getElementById("results").scrollIntoView({behavior:"smooth"});
  
}

  
 


