 const Ks = {	  
	  cost: 19,
	  use: 19,
	  weight: 18,
	  clarity: 18,
	  smoothness: 18,
	  comfort: 18,
	  friendship: 17,
	  mood: 17,
	  gender: 17,
	  luxury: 17,
	  natural: 17,
	  scale: 16,
	  calm: 15,
	  confidence: 15,
	  beauty: 14,
	  attractiveness: 14,
	  fashion: 14,
	  expressiveness: 14,
	  proportions: 13,
	  sophistication: 13,
	  harmony: 13,
	  density: 12,
	  thinness: 12,
	  pallor: 11,
	  thickness: 11,
	  roundness: 10,
	  acute: 10,
	  modernity: 9,
	  age: 9,
	  classically: 8,
	  simple: 8,
	  noble: 8,
	  lineary: 7,
	  familiar: 6,
	  exclusive: 6,
  }
  
  const pictures = {
	'Arial' : 'image/3.gif',
	'Blender Pro' : 'image/2.gif', 
	'Bebas' : 'image/3.gif',
	'Inter' : 'image/3.gif',
	'Decima Mono X' : 'image/6.gif',
	'Kizo' : 'image/5.gif',
	'PF DinText Pro' : 'image/3.gif',
	'PT Mono' : 'image/3.gif',
	'TT Firs Neue' : 'image/3.gif',
	'Circe' : 'image/3.gif',
	'Futura New Book' : 'image/5.gif',
	'Garamond Premier Pro' : 'image/5.gif',
	'Intro Black Alt' : 'image/1.gif',
	'Muller Regular' : 'image/3.gif',
	'ITC New Baskerville' : 'image/5.gif',
	'PF Regal Pro' : 'image/5.gif',
	'TTCommons' : 'image/3.gif',
	'Helvetica Neue' : 'image/3.gif',
	'Museo Cyrillic' : 'image/2.gif',
	'Neo Sans' : 'image/1.gif',
	'Stolzl' : 'image/3.gif',
	'Uni Sans Bold' : 'image/1.gif',
	'Code Pro Black' : 'image/6.gif',
	'Druk Wide' : 'image/6.gif',
	'Tactic Sans' : 'image/6.gif',
	'TT Supermolot Neue': 'image/5.gif',
	'Furore' : 'image/1.gif',
	'Vetren' : 'image/5.gif',
	'Trajan Pro' : 'image/5.gif',
	'Candara' : 'image/3.gif',
	'Thin Skinned' : 'image/1.gif',
	'Remains' : 'image/6.gif',
	'Road Rage' : 'image/6.gif',
	'Antonella' : 'image/4.gif',
	'Nostalgia' : 'image/1.gif',
	'Rosalinda' : 'image/4.gif',
	'Bernhard' : 'image/4.gif',
	'Rotonda' : 'image/3.gif',
	'KillCrazye' : 'image/6.gif',
	'Cinzel': 'image/5.gif',
	'Sverdlovsk' : 'image/2.gif',
	'Airfool' : 'image/1.gif',
	'NFS font' : 'image/6.gif',
	'EchoRevival' : 'image/1.gif',
	'AGOpus' : 'image/3.gif',
	'Grenouille' : 'image/1.gif',
	'Rum Raisin Cyrillic' : 'image/1.gif',
	'Mont ExtraLight' : 'image/2.gif',
	'Hacked' : 'image/6.gif',
	'Monotype Corsiva' : 'image/4.gif',
	'Cormorant Garamond' : 'image/2.gif',
	'Golos' : 'image/3.gif',
	'EB Garamond' : 'image/5.gif',
	'JetBrains Mono' : 'image/3.gif',
	'Whipsmart' : 'image/2.gif',
	'Noah' : 'image/3.gif',
	'Fira Sans' : 'image/3.gif',
	'PT Sans' : 'image/3.gif',
	'PT Root' : 'image/3.gif',
	'Pt Astra Serif' : 'image/2.gif',
	'Marta italic' : 'image/2.gif',
	'Sansation' : 'image/3.gif',
	'Literata' : 'image/3.gif',
	'Playfair Display' : 'image/5.gif',
	'Oranienbaum' : 'image/5.gif',
 	'Spectral' : 'image/5.gif',
	'Spectral SC' : 'image/5.gif',
	'Montserrat' : 'image/3.gif',
	'Akrobat' : 'image/3.gif',
	'Oks' : 'image/2.gif',
	'Misto' : 'image/6.gif',
	'Lora' : 'image/2.gif',
	'Sreda' : 'image/3.gif',
	'Bravo' : 'image/6.gif',
	'Bertha' : 'image/4.gif',
	'Caravan' : 'image/4.gif',
	'Keleti' : 'image/6.gif',
	'Palace of Sports' : 'image/4.gif',
	'Steelfish' : 'image/1.gif',
	'Movie' : 'image/1.gif',
	'Fedra Sans Pro' : 'image/3.gif',
	'Qanelas' : 'image/3.gif',
	'Twentytwelve Sans G' : 'image/1.gif',
	'Rodenko Condensed' : 'image/6.gif',
	'Ruberoid' : 'image/3.gif',
	'Anselm Sans' : 'image/3.gif',
	'Stinger' : 'image/2.gif',
	'Zapf Humanist' : 'image/5.gif',
	'Academy' : 'image/3.gif',
	'PF Centro Slab Pro' : 'image/3.gif',
	'TT Frantz' : 'image/1.gif',
	'Displace' : 'image/5.gif',
	'Ka Callista' : 'image/1.gif',
	'TT Knickerbockers Script' : 'image/4.gif',
	'Blackest' : 'image/6.gif',
	'TT Travels' : 'image/3.gif',
	'Blacker Sans Pro' : 'image/3.gif',
	'Berlingske Sans' : 'image/3.gif',
	'Cinematografica' : 'image/3.gif',
	'Spaceland' : 'image/3.gif',
	  
  }
  
  
  const complementaryFonts = {
	'1.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: Montserrat, Lora та Noah<br/><br/>Для шрифтового контрасту застосуйте: Vetren, PF Regal Pro чи Garamond Premier Pro',
	'2.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: Circe та Kizo<br/><br/>Для шрифтового контрасту застосуйте: Sreda,TT Supermolot Neue чи Rotonda',
	'3.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: TT Supermolot Neue та Pt Astra Serif<br/><br/>Для шрифтового контрасту застосуйте: Whipsmart, Thin Skinned чи Furore',
	'4.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: Helvetica Neue, Neo Sans, PT Root та Sansation',
	'5.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: Sverdlovsk, Mont ExtraLight та Akrobat<br/><br/>Для шрифтового контрасту застосуйте: Muller Regular, Circe чи Intro Black Alt',
	'6.gif' : 'Шрифтові пари для вас:<br/><br/>Гармонійно доповнять такі шрифти: Stolzl, PT Mono та Uni Sans Bold<br/><br/>Для шрифтового контрасту застосуйте: Bebas, Blender Pro чи Oranienbaum',
 }
  
  const FONTS = [
  {
	name: 'Arial',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Blender Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Bebas',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Inter',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Decima Mono X',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Kizo',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'b',
	  age: 'c',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'PF DinText Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'PT Mono',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },
  {
	name: 'TT Firs Neue',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'a',
	},
  },
  {
	name: 'Circe',
	characteristics:
	{		
		cost: 'c',
		use: 'b',

	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Futura New Book',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Garamond Premier Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'a',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Intro Black Alt',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'a',
	  classically: 'b',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Muller Regular',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'ITC New Baskerville',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'PF Regal Pro',
    characteristics:
	{		
		cost: 'a',
		use: 'b',

	  weight: 'b',
	  clarity: 'c',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'TTCommons',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Helvetica Neue',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Museo Cyrillic',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Neo Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Stolzl',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Uni Sans Bold',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Code Pro Black',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Druk Wide',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Tactic Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'TT Supermolot Neue',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Furore',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Vetren',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'a',
	  calm: 'c',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Trajan Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'b',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Candara',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'Thin Skinned',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Remains',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'c',
	  mood: 'a',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'c',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Road Rage',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Antonella',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Nostalgia',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'c',
	  classically: 'a',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rosalinda',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Bernhard',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rotonda',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'KillCrazye',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Cinzel',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'c',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },
  {
	name: 'Sverdlovsk',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },
  {
	name: 'Airfool',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'c',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'NFS font',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'EchoRevival',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'AGOpus',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Grenouille',
    characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'c',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'a',
	  beauty: 'c',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'c',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Rum Raisin Cyrillic',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'c',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Mont ExtraLight',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Hacked',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'c',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Monotype Corsiva',
	characteristics:
	{		
		cost: 'c',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'a',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Cormorant Garamond',
	characteristics:
	{		
		cost: 'a',
		use: 'b',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },
  {
	name: 'Golos',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

  {
	name: 'EB Garamond',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'c',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },

  {
	name: 'JetBrains Mono',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },

{
	name: 'Whipsmart',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Noah',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Fira Sans',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },

  {
	name: 'PT Sans',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },

  {
	name: 'PT Root',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'c',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },

{
	name: 'Pt Astra Serif',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'Marta italic',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Sansation',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },

  {
	name: 'Literata',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

  {
	name: 'Playfair Display',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },

{
	name: 'Oranienbaum',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'Spectral',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'a',
	},
  },
  {
	name: 'Spectral SC',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'c',
	  calm: 'c',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'b',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'b',
	  familiar: 'c',
	  exclusive: 'b',
	},
  },

  {
	name: 'Montserrat',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

  {
	name: 'Akrobat',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },

{
	name: 'Oks',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },
  {
	name: 'Misto',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'c',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Lora',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'b',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },

  {
	name: 'Sreda',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

  {
	name: 'Bravo',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },

{
	name: 'Bertha',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'c',
	  noble: 'b',
	  lineary: 'b',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Caravan',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'a',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'c',
	  natural: 'a',
	  scale: 'a',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'b',
	  exclusive: 'c',
	},
  },
  {
	name: 'Keleti',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'b',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'c',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },

  {
	name: 'Palace of Sports',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'c',
	  smoothness: 'a',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'c',
	  gender: 'a',
	  luxury: 'c',
	  natural: 'a',
	  scale: 'a',
	  calm: 'a',
	  confidence: 'a',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'b',
	  acute: 'c',
	  modernity: 'b',
	  age: 'c',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },

  {
	name: 'Steelfish',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

{
	name: 'Movie',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'a',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'b',
	  simple: 'a',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Fedra Sans Pro',
	characteristics:
	{		
		cost: 'a',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'a',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'a',
	  natural: 'a',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Qanelas',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'c',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'a',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },

  {
	name: 'Twentytwelve Sans G',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'c',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },

  {
	name: 'Rodenko Condensed',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'c',
	  age: 'c',
	  classically: 'b',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

{
	name: 'Ruberoid',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'c',
	  pallor: 'a',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Anselm Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },
  {
	name: 'Stinger',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'c',
	  modernity: 'a',
	  age: 'a',
	  classically: 'b',
	  simple: 'c',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },

  {
	name: 'Zapf Humanist',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'a',
	  proportions: 'a',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'a',
	  age: 'c',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'b',
	  exclusive: 'b',
	},
  },

  {
	name: 'Academy',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'a',
	  modernity: 'c',
	  age: 'b',
	  classically: 'a',
	  simple: 'b',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },

{
	name: 'PF Centro Slab Pro',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'c',
	  clarity: 'a',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'a',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'TT Frantz',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'c',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'a',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },
  {
	name: 'Displace',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'a',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'a',
	  modernity: 'a',
	  age: 'c',
	  classically: 'b',
	  simple: 'b',
	  noble: 'b',
	  lineary: 'b',
	  familiar: 'c',
	  exclusive: 'c',
	},
  },

  {
	name: 'Ka Callista',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'c',
	  clarity: 'c',
	  smoothness: 'b',
	  comfort: 'c',
	  friendship: 'b',
	  mood: 'a',
	  gender: 'b',
	  luxury: 'b',
	  natural: 'b',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'c',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'c',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'c',
	  lineary: 'b',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },

  {
	name: 'TT Knickerbockers Script',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'a',
	  mood: 'b',
	  gender: 'a',
	  luxury: 'b',
	  natural: 'a',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'a',
	  attractiveness: 'a',
	  fashion: 'a',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'b',
	  acute: 'c',
	  modernity: 'a',
	  age: 'b',
	  classically: 'c',
	  simple: 'c',
	  noble: 'c',
	  lineary: 'b',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },

{
	name: 'Blackest',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'c',
	  clarity: 'b',
	  smoothness: 'c',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'b',
	  confidence: 'b',
	  beauty: 'c',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'c',
	  proportions: 'b',
	  sophistication: 'c',
	  harmony: 'a',
	  density: 'a',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'a',
	  modernity: 'c',
	  age: 'b',
	  classically: 'c',
	  simple: 'b',
	  noble: 'c',
	  lineary: 'c',
	  familiar: 'a',
	  exclusive: 'c',
	},
  },
  {
	name: 'TT Travels',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'b',
	  density: 'c',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
  {
	name: 'Blacker Sans Pro',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'b',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },

  {
	name: 'Berlingske Sans',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'a',
	  friendship: 'b',
	  mood: 'b',
	  gender: 'b',
	  luxury: 'a',
	  natural: 'b',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'c',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'b',
	  pallor: 'c',
	  thickness: 'b',
	  roundness: 'c',
	  acute: 'b',
	  modernity: 'b',
	  age: 'b',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },

  {
	name: 'Cinematografica',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'a',
	  clarity: 'b',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'b',
	  natural: 'c',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'b',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'c',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'a',
	  harmony: 'a',
	  density: 'c',
	  thinness: 'a',
	  pallor: 'b',
	  thickness: 'a',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'c',
	  classically: 'a',
	  simple: 'a',
	  noble: 'b',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'b',
	},
  },

{
	name: 'Spaceland',
	characteristics:
	{		
		cost: 'c',
		use: 'c',
	  weight: 'b',
	  clarity: 'a',
	  smoothness: 'b',
	  comfort: 'b',
	  friendship: 'c',
	  mood: 'c',
	  gender: 'c',
	  luxury: 'a',
	  natural: 'c',
	  scale: 'b',
	  calm: 'a',
	  confidence: 'c',
	  beauty: 'b',
	  attractiveness: 'b',
	  fashion: 'b',
	  expressiveness: 'b',
	  proportions: 'b',
	  sophistication: 'b',
	  harmony: 'a',
	  density: 'b',
	  thinness: 'c',
	  pallor: 'c',
	  thickness: 'c',
	  roundness: 'a',
	  acute: 'b',
	  modernity: 'b',
	  age: 'c',
	  classically: 'b',
	  simple: 'a',
	  noble: 'a',
	  lineary: 'a',
	  familiar: 'a',
	  exclusive: 'a',
	},
  },
]
function myFunction() {
  var form = document.querySelector("form");
  var data = new FormData(form);
  
  const results = FONTS.map(f => {
	  const characteristics = Object.keys(f.characteristics);
	  
	  const score = characteristics.reduce((res, character) => {
		  const userValue = data.get(character) || "b";
		  const k = Ks[character];
		  
		  let charScore = userValue === f.characteristics[character] ? 1 : -1;
		  if (userValue=="b" || f.characteristics[character]=="b") {
			  charScore = 0;
		  }
		  return res + charScore * k;
		  
	  }, 0);
	  
	  return {
		  name: f.name,
		  score: score
	  }
	  
  })
  
  
  
  results.sort(function(a,b){return b.score-a.score});
  console.log(results);
   
  document.getElementById("results").style.display="block";
  
  
  document.getElementById("first").textContent="1. " + results[0].name;
  document.getElementById("second").textContent="2. " + results[1].name;
  document.getElementById("third").textContent="3. " + results[2].name;
  document.getElementById("fourth").textContent="4. " + results[3].name;
  document.getElementById("fifth").textContent="5. " + results[4].name;
  
 console.log(results[2].name);
  document.getElementById("first").style.fontFamily=results[0].name;
  document.getElementById("second").style.fontFamily=results[1].name;
  document.getElementById("third").style.fontFamily=results[2].name;
  document.getElementById("fourth").style.fontFamily=results[3].name;
  document.getElementById("fifth").style.fontFamily=results[4].name;
  
  document.getElementById("picture").src=pictures[results[0].name];
  document.getElementById("complementary").innerHTML='';
  document.getElementById("complementary").insertAdjacentHTML('afterbegin',complementaryFonts[document.getElementById("picture").src.slice(-5)]);
  //console.log(complementaryFonts[document.getElementById("picture").src.slice(-5)]);
  
  document.getElementById("results").scrollIntoView({behavior:"smooth"});
}
